name: jupyterlab-plugin-graph-demo
channels:
- conda-forge/label/jupyterlab_rc
- conda-forge/label/jupyterlab_server_rc
- conda-forge
dependencies:
- jupyterlab=3
- nodejs
- pip
- python
- pip:
  - jupyterlab-plugin-graph
